-- init-scripts/001-create-schemas.sql
-- Crear schema auth
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS product;
CREATE SCHEMA IF NOT EXISTS tables;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS cook;
CREATE SCHEMA IF NOT EXISTS billing;

-- Crear usuario si no existe (por si acaso)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'isaii_postgre_admin') THEN
        CREATE USER isaii_postgre_admin WITH PASSWORD 'isaii2-2025-2';
    END IF;
END
$$;

-- Otorgar todos los permisos
GRANT ALL PRIVILEGES ON DATABASE isaii_app TO isaii_postgre_admin;
GRANT ALL PRIVILEGES ON SCHEMA auth TO isaii_postgre_admin;
GRANT ALL PRIVILEGES ON SCHEMA product TO isaii_postgre_admin;
GRANT ALL PRIVILEGES ON SCHEMA tables TO isaii_postgre_admin;
GRANT ALL PRIVILEGES ON SCHEMA orders TO isaii_postgre_admin;
GRANT ALL PRIVILEGES ON SCHEMA cook TO isaii_postgre_admin;
GRANT ALL PRIVILEGES ON SCHEMA billing TO isaii_postgre_admin;
GRANT ALL PRIVILEGES ON SCHEMA public TO isaii_postgre_admin;

-- Para tablas futuras
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL PRIVILEGES ON TABLES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL PRIVILEGES ON SEQUENCES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA product GRANT ALL PRIVILEGES ON TABLES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA product GRANT ALL PRIVILEGES ON SEQUENCES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA tables GRANT ALL PRIVILEGES ON TABLES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA tables GRANT ALL PRIVILEGES ON SEQUENCES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT ALL PRIVILEGES ON TABLES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT ALL PRIVILEGES ON SEQUENCES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA cook GRANT ALL PRIVILEGES ON TABLES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA cook GRANT ALL PRIVILEGES ON SEQUENCES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT ALL PRIVILEGES ON TABLES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT ALL PRIVILEGES ON SEQUENCES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO isaii_postgre_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO isaii_postgre_admin;

-- Mensaje de confirmación
SELECT 'Schemas creados exitosamente' as status;
