# docker-compose.yml
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/isaii_app
      - SPRING_DATASOURCE_USERNAME=isaii_postgre_admin
      - SPRING_DATASOURCE_PASSWORD=isaii2-2025-2
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./test-reports:/app/build/reports/tests
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=isaii_app
      - POSTGRES_USER=isaii_postgre_admin
      - POSTGRES_PASSWORD=isaii2-2025-2
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U isaii_postgre_admin -d isaii_app"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge